export const sampleBooks = [
  {
    id: 1,
    title: "The Midnight Library",
    author: "Matt Haig",
    genre: "Fantasy / Fiction",
    rating: 4.6,
    total_copies: 20,
    available_copies: 10,
    description:
      "A dazzling novel about all the choices that go into a life well lived.",
    color: "#1c1f40",
    cover: "https://m.media-amazon.com/images/I/81J6APjwxlL.jpg",
    video: "/sample-video.mp4",
    summary:
      "A story exploring regrets, alternate lives, and the beauty of possibility.",
  },
  {
    id: 2,
    title: "Atomic Habits",
    author: "James Clear",
    genre: "Self-help / Productivity",
    rating: 4.8,
    total_copies: 25,
    available_copies: 15,
    description:
      "An easy & proven way to build good habits and break bad ones.",
    color: "#2f4858",
    cover: "https://m.media-amazon.com/images/I/91bYsX41DVL.jpg",
    video: "/sample-video.mp4",
    summary: "Learn how tiny changes lead to remarkable results.",
  },
  {
    id: 3,
    title: "Dune",
    author: "Frank Herbert",
    genre: "Science Fiction",
    rating: 4.7,
    total_copies: 30,
    available_copies: 22,
    description: "A mythic and emotionally charged hero’s journey.",
    color: "#4a2c2a",
    cover: "https://m.media-amazon.com/images/I/91A5h1tNQzL.jpg",
    video: "/sample-video.mp4",
    summary: "Set on the desert planet Arrakis, the story of Paul Atreides.",
  },
  {
    id: 4,
    title: "Becoming",
    author: "Michelle Obama",
    genre: "Biography / Memoir",
    rating: 4.9,
    total_copies: 18,
    available_copies: 9,
    description:
      "An intimate, powerful, and inspiring memoir by the former First Lady.",
    color: "#2c3e50",
    cover: "https://m.media-amazon.com/images/I/81h2gWPTYJL.jpg",
    video: "/sample-video.mp4",
    summary: "A deeply personal reckoning of a remarkable woman.",
  },
  {
    id: 5,
    title: "1984",
    author: "George Orwell",
    genre: "Dystopian / Political Fiction",
    rating: 4.7,
    total_copies: 40,
    available_copies: 35,
    description: "A chilling dystopia that has become eerily relevant today.",
    color: "#3d3d3d",
    cover: "https://m.media-amazon.com/images/I/71kxa1-0mfL.jpg",
    video: "/sample-video.mp4",
    summary: "A world of constant surveillance and mind control.",
  },
  {
    id: 6,
    title: "Where the Crawdads Sing",
    author: "Delia Owens",
    genre: "Mystery / Fiction",
    rating: 4.6,
    total_copies: 22,
    available_copies: 11,
    description: "A haunting mystery and coming-of-age tale.",
    color: "#5c3c25",
    cover: "https://m.media-amazon.com/images/I/81WWiiLgRZL.jpg",
    video: "/sample-video.mp4",
    summary: "Set in the marshes of North Carolina.",
  },
  {
    id: 7,
    title: "The Alchemist",
    author: "Paulo Coelho",
    genre: "Adventure / Spiritual",
    rating: 4.5,
    total_copies: 30,
    available_copies: 14,
    description: "A philosophical book about following your dreams.",
    color: "#b3704c",
    cover: "https://m.media-amazon.com/images/I/71aFt4+OTOL.jpg",
    video: "/sample-video.mp4",
    summary: "A journey of self-discovery through the desert.",
  },
  {
    id: 8,
    title: "Educated",
    author: "Tara Westover",
    genre: "Memoir",
    rating: 4.7,
    total_copies: 20,
    available_copies: 10,
    description: "A memoir about breaking free from a survivalist upbringing.",
    color: "#7c8a79",
    cover: "https://m.media-amazon.com/images/I/81WojUxbbFL.jpg",
    video: "/sample-video.mp4",
    summary: "One woman’s journey to education and self-empowerment.",
  },
  {
    id: 9,
    title: "It Ends With Us",
    author: "Colleen Hoover",
    genre: "Romance / Drama",
    rating: 4.3,
    total_copies: 25,
    available_copies: 13,
    description: "A powerful story of love, strength, and letting go.",
    color: "#d989b5",
    cover: "https://m.media-amazon.com/images/I/81s0B6NYXML.jpg",
    video: "/sample-video.mp4",
    summary: "A tale of complicated choices and emotional growth.",
  },
  {
    id: 10,
    title: "Project Hail Mary",
    author: "Andy Weir",
    genre: "Science Fiction / Thriller",
    rating: 4.8,
    total_copies: 35,
    available_copies: 28,
    description: "A lone astronaut must save Earth from disaster.",
    color: "#10121b",
    cover: "https://m.media-amazon.com/images/I/91c5Ffrrw4L.jpg",
    video: "/sample-video.mp4",
    summary: "High-stakes space adventure with brilliant science.",
  },
  {
    id: 11,
    title: "The Book Thief",
    author: "Markus Zusak",
    genre: "Historical Fiction",
    rating: 4.6,
    total_copies: 28,
    available_copies: 16,
    description: "A story of a girl who finds solace in books during WWII.",
    color: "#633c2d",
    cover: "https://m.media-amazon.com/images/I/81-3504YVML.jpg",
    video: "/sample-video.mp4",
    summary: "Narrated by Death, the tale of a powerful journey.",
  },
  {
    id: 12,
    title: "The Subtle Art of Not Giving a F*ck",
    author: "Mark Manson",
    genre: "Self-help / Humor",
    rating: 4.4,
    total_copies: 30,
    available_copies: 21,
    description: "A counterintuitive approach to living a good life.",
    color: "#f35e2d",
    cover: "https://m.media-amazon.com/images/I/71QKQ9mwV7L.jpg",
    video: "/sample-video.mp4",
    summary: "Accept your flaws and focus on what really matters.",
  },
  {
    id: 13,
    title: "The Silent Patient",
    author: "Alex Michaelides",
    genre: "Psychological Thriller",
    rating: 4.3,
    total_copies: 22,
    available_copies: 9,
    description: "A woman stops speaking after a shocking act of violence.",
    color: "#a1a1a1",
    cover: "https://m.media-amazon.com/images/I/71o1E3kO5aL.jpg",
    video: "/sample-video.mp4",
    summary: "A twisty psychological thriller with a shocking ending.",
  },
  {
    id: 14,
    title: "The Seven Husbands of Evelyn Hugo",
    author: "Taylor Jenkins Reid",
    genre: "Historical Fiction / Romance",
    rating: 4.6,
    total_copies: 18,
    available_copies: 7,
    description: "A legendary actress reveals her life's hidden truths.",
    color: "#21443c",
    cover: "https://m.media-amazon.com/images/I/81t+6kK6FML.jpg",
    video: "/sample-video.mp4",
    summary: "A powerful exploration of love, fame, and identity.",
  },
  {
    id: 15,
    title: "Rich Dad Poor Dad",
    author: "Robert T. Kiyosaki",
    genre: "Finance / Education",
    rating: 4.4,
    total_copies: 30,
    available_copies: 18,
    description: "What the rich teach their kids about money.",
    color: "#3d2e5a",
    cover: "https://m.media-amazon.com/images/I/81bsw6fnUiL.jpg",
    video: "/sample-video.mp4",
    summary: "Shift your mindset on money, assets, and income.",
  },
  {
    id: 16,
    title: "The Power of Now",
    author: "Eckhart Tolle",
    genre: "Spiritual / Mindfulness",
    rating: 4.5,
    total_copies: 24,
    available_copies: 12,
    description: "Guide to spiritual enlightenment and presence.",
    color: "#8ac0a0",
    cover: "https://m.media-amazon.com/images/I/61pHff60-vL.jpg",
    video: "/sample-video.mp4",
    summary: "Find peace and meaning through present awareness.",
  },
  {
    id: 17,
    title: "The Hunger Games",
    author: "Suzanne Collins",
    genre: "Dystopian / YA Fiction",
    rating: 4.7,
    total_copies: 35,
    available_copies: 20,
    description: "A fight to survive in a televised death match.",
    color: "#1d1d1d",
    cover: "https://m.media-amazon.com/images/I/91uZqWUMxrL.jpg",
    video: "/sample-video.mp4",
    summary: "Katniss Everdeen becomes a symbol of rebellion.",
  },
  {
    id: 18,
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    genre: "Psychology / Economics",
    rating: 4.5,
    total_copies: 20,
    available_copies: 14,
    description: "Explore the two systems that drive how we think.",
    color: "#ffffff",
    cover: "https://m.media-amazon.com/images/I/71nR9G7LUzL.jpg",
    video: "/sample-video.mp4",
    summary: "A deep dive into decision-making and cognitive bias.",
  },
  {
    id: 19,
    title: "Sapiens",
    author: "Yuval Noah Harari",
    genre: "History / Anthropology",
    rating: 4.7,
    total_copies: 25,
    available_copies: 20,
    description: "A brief history of humankind from evolution to modernity.",
    color: "#d8cdc4",
    cover: "https://m.media-amazon.com/images/I/713jIoMO3UL.jpg",
    video: "/sample-video.mp4",
    summary: "Explore how humans became the planet’s dominant species.",
  },
  {
    id: 20,
    title: "A Court of Thorns and Roses",
    author: "Sarah J. Maas",
    genre: "Fantasy / Romance",
    rating: 4.5,
    total_copies: 20,
    available_copies: 8,
    description: "A huntress gets entangled in a world of fae.",
    color: "#592b2b",
    cover: "https://m.media-amazon.com/images/I/81QZV6zb-1L.jpg",
    video: "/sample-video.mp4",
    summary: "Romance and danger collide in this magical series.",
  },
];
